### ISSUE TITLE
Build pipeline failed with azure

### ISSUE THREAD

**Issue by infohliang** [bauca/PythonAPIAzureQuickstart#5]
Hi,
Thanks for sharing. I have tried to setup the build pipeline in azure with azure container registery and get below error:

```
Step 6/19 : RUN poetry install
 ---> Running in f06e7d5e44e6

  RuntimeError

  Poetry could not find a pyproject.toml file in /backend or its parents

  at /usr/local/lib/python3.10/site-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
The command '/bin/sh -c poetry install' returned a non-zero code: 1
##[error]The command '/bin/sh -c poetry install' returned a non-zero code: 1
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Build and push an image to container registry
```

My azure-pipelines.yml file looks like this ( I haven't figure out how to add the unit tests and deploy to the tasks yet):

trigger:
- main```

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'xxxxxx'
  imageRepository: 'someimg'
  containerRegistry: 'somereporeg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/deploy/docker/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
```


any reason why?
Thank you

**Comment by bauca** [comment]
Hi, 
It looks like while trying to build the image, the context is missing (docker can't find the Python files and the poetry config file), I believe adding the 'buildContext' argument, pointing to the correct path, should do the job. Give it a try:

```
trigger:
- main

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'xxxxxx'
  imageRepository: 'someimg'
  containerRegistry: 'somereporeg.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/deploy/docker/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        buildContext: $(Build.SourcesDirectory)
        tags: |
          $(tag)
```

**Comment by bauca** [comment]
Additionally:
As you are using the Azure Container Registry, you'll also need to log into it to push you images there, before your buildAndPush task, you should add the login task, and reference your service connection.

```
steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: dockerRegistryServiceConnection1
```
